"""empty message

Revision ID: aed5ef438fc7
Revises: 7e35565a1d8d
Create Date: 2019-11-09 20:58:29.226784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed5ef438fc7'
down_revision = '7e35565a1d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
