"""empty message

Revision ID: f636d221ce0d
Revises: ee352d1c62b5
Create Date: 2019-11-12 00:22:28.927598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f636d221ce0d'
down_revision = 'ee352d1c62b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'post_id')
    # ### end Alembic commands ###
